config/routes.rb
TwiApp::Application.routes.draw do
    
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :quests
  resources :media, :controller => "medias"

    root to: 'static_pages#home'
  

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/links',   to: 'static_pages#links'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  
  

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    V.Ilinicz:
    %a{"data-background-color" => "#990000",:href => "http://vk.com/id103234803"} VK
    |
    %a{:href => "http://www.facebook.com/vincent.ilinich"} FB
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Links", links_path
      %li= link_to "Contact", contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "SR", root_path, id: "logo"
      %nav
        = form_tag quests_path, :method => 'get', class: 'navbar-search pull-right' do
          = text_field_tag :search_text, params[:search_text], class: 'search-query'
        %ul.nav.pull-right
          %li= link_to "Media", media_path
          %li.divider-vertical
          - if signed_in?
            %li= link_to "Users", users_path
            %li.divider-vertical
            %li#fat-menu.dropdown.pull-right
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                = first_two_of_name(current_user.name)
                %b.caret
              %ul.dropdown-menu
                %li= link_to "My Page", root_path
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = google_webfonts_init({google: ['Titillium Web']})
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = render 'layouts/footer'
      = debug(params) if  Rails.env.development?